########## Testcase 0: Failed ##########
Expected Output: 
76.8
6

Your Output: 
Traceback (most recent call last):
  File "solution.py", line 48, in <module>
    main()
  File "solution.py", line 25, in main
    print(lister(input1,templen))
NameError: name 'templen' is not defined
----------------------------------------

########## Testcase 1: Failed ##########
Expected Output: 
5.5
1

Your Output: 
Traceback (most recent call last):
  File "solution.py", line 48, in <module>
    main()
  File "solution.py", line 25, in main
    print(lister(input1,templen))
NameError: name 'templen' is not defined
----------------------------------------

########## Testcase 2: Failed ##########
Expected Output: 
1
6

Your Output: 
Traceback (most recent call last):
  File "solution.py", line 48, in <module>
    main()
  File "solution.py", line 25, in main
    print(lister(input1,templen))
NameError: name 'templen' is not defined
----------------------------------------

########## Testcase 3: Failed ##########
Expected Output: 
5
4

Your Output: 
Traceback (most recent call last):
  File "solution.py", line 48, in <module>
    main()
  File "solution.py", line 25, in main
    print(lister(input1,templen))
NameError: name 'templen' is not defined
----------------------------------------

########## Testcase 4: Failed ##########
Expected Output: 
0
8

Your Output: 
Traceback (most recent call last):
  File "solution.py", line 48, in <module>
    main()
  File "solution.py", line 25, in main
    print(lister(input1,templen))
NameError: name 'templen' is not defined
----------------------------------------

########## Testcase 5: Failed ##########
Expected Output: 
5654134.9
10

Your Output: 
Traceback (most recent call last):
  File "solution.py", line 48, in <module>
    main()
  File "solution.py", line 25, in main
    print(lister(input1,templen))
NameError: name 'templen' is not defined
----------------------------------------

